name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_RESOURCE_GROUP: 'RG-WEB-DEPLOY'
  AZURE_REGION: 'eastus2'
  BICEP_FILE_PATH: 'infra/bicep/main.bicep'
  BICEP_PARAMETERS_FILE: 'infra/bicep/parameters/main.bicepparam'
  ARM_PARAMETERS_FILE: 'artifact/infra/bicep/parameters/main.parameters.json'
permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ./src/dotnet/AzureDeploymentWeb/AzureDeploymentWeb.csproj
      
    - name: Build application
      run: dotnet build ./src/dotnet/AzureDeploymentWeb/AzureDeploymentWeb.csproj --configuration Release --no-restore
      
    - name: Run Unit Tests
      run: dotnet test ./src/dotnet/AzureDeploymentWeb.Tests/AzureDeploymentWeb.Tests.csproj --configuration Release --logger trx --results-directory TestResults
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: TestResults/*.trx
        reporter: dotnet-trx
        
    - name: Publish application
      run: dotnet publish ./src/dotnet/AzureDeploymentWeb/AzureDeploymentWeb.csproj --configuration Release --output ./publish --no-build
      
    - name: Create deployment package
      run: cd publish && zip -r ../publish.zip .
    
    - name: Validate Bicep and Prepare Parameters
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az bicep build --file ${{ env.BICEP_FILE_PATH }} --outdir infra/bicep
          az bicep build-params --file ${{ env.BICEP_PARAMETERS_FILE }} --outfile infra/bicep/parameters/main.parameters.json
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp-build
        path: |
          ./publish.zip
          ./infra/bicep/**
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp-build
        path: ./artifact
        
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: Deploy Bicep Infrastructure
      id: bicep-deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: artifact/infra/bicep/main.bicep
        parameters: ${{ env.ARM_PARAMETERS_FILE }} azureAdClientSecret=${{ secrets.AZURE_AD_CLIENT_SECRET }}
        failOnStdErr: false
        deploymentName: main-${{ github.run_id }}
        scope: resourcegroup
        
    - name: Deploy Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ steps.bicep-deploy.outputs.webAppName }}
        package: artifact/publish.zip
        type: 'ZIP'

  playwright-tests:
    needs: deploy
    runs-on: ubuntu-latest
    if: success()
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Playwright dependencies
      run: |
        cd tests/playwright
        npm install
        
    - name: Install Playwright Browsers
      run: |
        cd tests/playwright
        npx playwright install --with-deps
        
    - name: Run Playwright tests
      run: |
        cd tests/playwright
        npm run test
      env:
        BASE_URL: ${{ steps.bicep-deploy.outputs.webAppUrl || format('https://{0}.azurewebsites.net', steps.bicep-deploy.outputs.webAppName) }}
        
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: tests/playwright/playwright-report/
        retention-days: 30